addSbtPlugin("org.scalameta"    % "sbt-scalafmt"            % "2.4.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"     % "1.3.22")
addSbtPlugin("org.duhemm"       % "sbt-errors-summary"      % "0.6.3")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"         % "2.4.10")
addSbtPlugin("org.wartremover"  % "sbt-wartremover-contrib" % "1.3.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"           % "1.5.1")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"            % "0.15.0")
